-- Tabela de Tanques
CREATE TABLE TANQUES (
  ID INTEGER NOT NULL PRIMARY KEY,
  TIPO_COMBUSTIVEL VARCHAR(20) NOT NULL,
  CAPACIDADE_LITROS NUMERIC(15,2) NOT NULL,
  ESTOQUE_ATUAL NUMERIC(15,2) NOT NULL
);

-- Tabela de Bombas
CREATE TABLE BOMBAS (
  ID INTEGER NOT NULL PRIMARY KEY,
  NUMERO_BOMBA INTEGER NOT NULL,
  TANQUE_ID INTEGER NOT NULL,
  FOREIGN KEY (TANQUE_ID) REFERENCES TANQUES(ID)
);

-- Tabela de Abastecimentos
CREATE TABLE ABASTECIMENTOS (
  ID INTEGER NOT NULL PRIMARY KEY,
  BOMBA_ID INTEGER NOT NULL,
  DATA_HORA TIMESTAMP NOT NULL,
  LITROS NUMERIC(15,2) NOT NULL,
  VALOR_TOTAL NUMERIC(15,2) NOT NULL,
  IMPOSTO NUMERIC(15,2) NOT NULL,
  VALOR_COM_IMPOSTO NUMERIC(15,2) NOT NULL,
  FOREIGN KEY (BOMBA_ID) REFERENCES BOMBAS(ID)
);

-- Generators (Sequences) para IDs
CREATE GENERATOR GEN_TANQUES_ID;
CREATE GENERATOR GEN_BOMBAS_ID;
CREATE GENERATOR GEN_ABASTECIMENTOS_ID;

-- Inserir dados iniciais - 2 Tanques
INSERT INTO TANQUES (ID, TIPO_COMBUSTIVEL, CAPACIDADE_LITROS, ESTOQUE_ATUAL)
VALUES (1, 'GASOLINA', 10000.00, 10000.00);

INSERT INTO TANQUES (ID, TIPO_COMBUSTIVEL, CAPACIDADE_LITROS, ESTOQUE_ATUAL)
VALUES (2, 'DIESEL', 10000.00, 10000.00);

-- Inserir 4 Bombas (2 para cada tanque)
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (1, 1, 1);
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (2, 2, 1);
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (3, 3, 2);
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (4, 4, 2);

-- Commit
COMMIT;
