
SET TERM !! ;

CREATE TRIGGER BI_TANQUES FOR TANQUES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_TANQUES_ID, 1);
END
!!

CREATE TRIGGER BI_BOMBAS FOR BOMBAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_BOMBAS_ID, 1);
END
!!

CREATE TRIGGER BI_ABASTECIMENTOS FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_ABASTECIMENTOS_ID, 1);
END
!!

SET TERM ; !!
COMMIT;
