
SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  BEGIN
    EXECUTE STATEMENT 'DROP TRIGGER BI_ABASTECIMENTOS';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP TRIGGER BI_BOMBAS';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP TRIGGER BI_TANQUES';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP TABLE ABASTECIMENTOS';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP TABLE BOMBAS';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP TABLE TANQUES';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP GENERATOR GEN_ABASTECIMENTOS_ID';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP GENERATOR GEN_BOMBAS_ID';
  WHEN ANY DO
    BEGIN END
  END

  BEGIN
    EXECUTE STATEMENT 'DROP GENERATOR GEN_TANQUES_ID';
  WHEN ANY DO
    BEGIN END
  END
END
^

SET TERM ; ^

COMMIT;

-- 1) Criar generators
CREATE GENERATOR GEN_TANQUES_ID;
CREATE GENERATOR GEN_BOMBAS_ID;
CREATE GENERATOR GEN_ABASTECIMENTOS_ID;

-- 2) Criar tabelas
CREATE TABLE TANQUES (
  ID INTEGER NOT NULL,
  TIPO_COMBUSTIVEL VARCHAR(20) NOT NULL,
  CAPACIDADE_LITROS DECIMAL(15,2) NOT NULL,
  ESTOQUE_ATUAL DECIMAL(15,2) NOT NULL,
  CONSTRAINT PK_TANQUES PRIMARY KEY (ID)
);

CREATE TABLE BOMBAS (
  ID INTEGER NOT NULL,
  NUMERO_BOMBA INTEGER NOT NULL,
  TANQUE_ID INTEGER NOT NULL,
  CONSTRAINT PK_BOMBAS PRIMARY KEY (ID),
  CONSTRAINT FK_BOMBAS_TANQUES FOREIGN KEY (TANQUE_ID) REFERENCES TANQUES (ID)
);

CREATE TABLE ABASTECIMENTOS (
  ID INTEGER NOT NULL,
  BOMBA_ID INTEGER NOT NULL,
  DATA_HORA TIMESTAMP NOT NULL,
  LITROS DECIMAL(15,2) NOT NULL,
  VALOR_TOTAL DECIMAL(15,2) NOT NULL,
  IMPOSTO DECIMAL(15,2) NOT NULL,
  VALOR_COM_IMPOSTO DECIMAL(15,2) NOT NULL,
  CONSTRAINT PK_ABASTECIMENTOS PRIMARY KEY (ID),
  CONSTRAINT FK_ABASTECIMENTOS_BOMBAS FOREIGN KEY (BOMBA_ID) REFERENCES BOMBAS (ID)
);

COMMIT;

-- 3) Inserções iniciais (inserindo explicitamente os IDs)
INSERT INTO TANQUES (ID, TIPO_COMBUSTIVEL, CAPACIDADE_LITROS, ESTOQUE_ATUAL)
VALUES (1, 'GASOLINA', 10000.00, 10000.00);

INSERT INTO TANQUES (ID, TIPO_COMBUSTIVEL, CAPACIDADE_LITROS, ESTOQUE_ATUAL)
VALUES (2, 'DIESEL', 10000.00, 10000.00);

INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (1, 1, 1);
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (2, 2, 1);
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (3, 3, 2);
INSERT INTO BOMBAS (ID, NUMERO_BOMBA, TANQUE_ID) VALUES (4, 4, 2);

COMMIT;

-- 4) Criar triggers (usa delimitadores diferentes para suportar o corpo das triggers)
SET TERM !! ;

CREATE TRIGGER BI_TANQUES FOR TANQUES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_TANQUES_ID, 1);
END
!!

CREATE TRIGGER BI_BOMBAS FOR BOMBAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_BOMBAS_ID, 1);
END
!!

CREATE TRIGGER BI_ABASTECIMENTOS FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_ABASTECIMENTOS_ID, 1);
END
!!

SET TERM ; !!

COMMIT;

-- 5) Sincronizar generators com os IDs atuais (ajusta para o maior ID inserido)
-- Ajustamos manualmente com os maiores valores usados nas inserções acima.
SET GENERATOR GEN_TANQUES_ID TO 2;
SET GENERATOR GEN_BOMBAS_ID TO 4;
SET GENERATOR GEN_ABASTECIMENTOS_ID TO 0;

COMMIT;
